### ISSUE TITLE
NPM install not working

### ISSUE THREAD

**Issue by mwlock** [szmarczak/http-timer#22]
Hi there, I am receiving the following error when trying to install the package with ``npm install @szmarczak/http-timer``

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-4.0.5.tgz
npm ERR! 404
npm ERR! 404  '@szmarczak/http-timer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user-pc\AppData\Roaming\npm-cache\_logs\2020-08-06T09_55_40_842Z-debug.log
PS D:\Udemy\nodejs\deployed_apps\lord_fay> npm install @szmarczak/http-timer
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@szmarczak/http-timer/-/http-timer-4.0.5.tgz
npm ERR! 404
npm ERR! 404  '@szmarczak/http-timer@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user-pc\AppData\Roaming\npm-cache\_logs\2020-08-06T09_58_09_599Z-debug.log
```

**Comment by moha-verse** [comment]
Hi 
I am facing the same. npm install is failing due to this issue.

**Comment by fradifan** [comment]
is it caused by this npm problem?
https://status.npmjs.org/#

**Comment by JEBDevOps** [comment]
Hi. Same issue here. Our github actions started to act up and the error pointed to Yarn being unable to find this particular package.

**Comment by duongvanba** [comment]
Me too

**Comment by mwlock** [comment]
> is it caused by this npm problem?
> https://status.npmjs.org/#

I think you might be right

**Comment by szmarczak** [comment]
Seems like this is fixed on the NPM side. Can you confirm on your side?

**Comment by NathanHazout** [comment]
It's back online now for me

**Comment by mwlock** [comment]
> It's back online now for me

Everything working now!

**Comment by muiux** [comment]
I am still facing this issue even it's online

**Comment by em-winterschon** [comment]
This is still a problem

```
600 error HTTPError: Response code 404 (Not Found)
600 error     at Request._onResponseBase (/home/eva/Projects/electron/comms/node_modules/got/dist/source/core/index.js:913:31)
600 error     at Request._onResponse (/home/eva/Projects/electron/comms/node_modules/got/dist/source/core/index.js:948:24)
600 error     at ClientRequest.<anonymous> (/home/eva/Projects/electron/comms/node_modules/got/dist/source/core/index.js:962:23)
600 error     at Object.onceWrapper (node:events:633:26)
600 error     at ClientRequest.emit (node:events:530:35)
600 error     at origin.emit (/home/eva/Projects/electron/comms/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
600 error     at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)
600 error     at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
600 error     at TLSSocket.socketOnData (node:_http_client:535:22)
600 error     at TLSSocket.emit (node:events:518:28)
601 verbose exit 1
```
