### ISSUE TITLE
404 on `npm install` [OpenBSD 7.2]

### ISSUE THREAD

**Issue by iiisak** [szmarczak/http-timer#32]
Trying to install `@szmarczak/http-timer` on OpenBSD 7.2 fails:
```
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm ERR! code 1
npm ERR! path /home/isak/WebCord/node_modules/electron
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! HTTPError: Response code 404 (Not Found)
npm ERR!     at Request._onResponseBase (/home/isak/WebCord/node_modules/got/dist/source/core/index.js:913:31)
npm ERR!     at Request._onResponse (/home/isak/WebCord/node_modules/got/dist/source/core/index.js:948:24)
npm ERR!     at ClientRequest.<anonymous> (/home/isak/WebCord/node_modules/got/dist/source/core/index.js:962:23)
npm ERR!     at Object.onceWrapper (node:events:628:26)
npm ERR!     at ClientRequest.emit (node:events:525:35)
npm ERR!     at ClientRequest.origin.emit (/home/isak/WebCord/node_modules/got/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
npm ERR!     at HTTPParser.parserOnIncomingClient (node:_http_client:674:27)
npm ERR!     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
npm ERR!     at TLSSocket.socketOnData (node:_http_client:521:22)
npm ERR!     at TLSSocket.emit (node:events:513:28)
```

**Comment by szmarczak** [comment]
I just verified that `npm install @szmarczak/http-timer` does not fail.
